package com.josewolf.estoque_api.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.util.List;

public record CategoryResponseDTO(
        @Schema(description = "Id unique generated by the database", example = "1")
        Long id,

        @Schema(description = "Return title", example = "Electronics.")
        String category,

        @Schema(description = "Return a products list", example = "iPhone, Samsung S26, Kindle.")
        List<ProductResponseDTO> products
) {

    @Schema(description = "Total sum of the stock value for all products in this category", example = "1500.00")
    public BigDecimal getCategoryValue(){
        return products.stream()
                .map(ProductResponseDTO::getTotalStockValue)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }
}
