package com.josewolf.estoque_api.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;

public record ProductResponseDTO(

        @Schema(description = "Id unique generated by the database", example = "1")
        Long id,
        @Schema(description = "Return the product name", example = "Kindle")
        String productName,
        @Schema(description = "Return the description of product", example = "Kindle 16gb 11 generation, color: Black or Green")
        String description,
        @Schema(example = "98.90")
        BigDecimal price,
        @Schema(example = "10")
        Integer quantity,
        @Schema(description = "Returns the category name of product", example = "The Kindle belongs to the electronics category")
        String categoryName,
        @Schema(description = "The id of category")
        Long categoryId
) {

    @Schema(description = "Total of a quantity multiplied by a price.", example = "Kindle total is 989.00")
    public BigDecimal getTotalStockValue() {
        if(price == null || quantity == null){
            return BigDecimal.ZERO;
        }
        return price.multiply(BigDecimal.valueOf(quantity));
    }
}
